// actionTypes.js
export const SET_OPEN_CONFIGURATOR = "SET_OPEN_CONFIGURATOR";
export const SET_SIDENAV_COLOR = "SET_SIDENAV_COLOR";
export const SET_SIDENAV_TYPE = "SET_SIDENAV_TYPE";
export const SET_FIXED_NAVBAR = "SET_FIXED_NAVBAR";
export const SET_OPEN_SIDENAV = "SET_OPEN_SIDENAV";
